# Generated by Django 4.1.5 on 2023-01-24 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='domain',
            old_name='title',
            new_name='name',
        ),
    ]
