# Generated by Django 4.1.5 on 2023-01-25 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter_app', '0004_alter_article_article_file_alter_article_photo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='article_file',
            field=models.FileField(upload_to='uploads/article/file'),
        ),
        migrations.AlterField(
            model_name='article',
            name='photo',
            field=models.ImageField(upload_to='uploads/article/image'),
        ),
        migrations.AlterField(
            model_name='domain',
            name='photo',
            field=models.ImageField(upload_to='uploads/domain'),
        ),
    ]
