# Generated by Django 4.1.5 on 2023-01-31 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter_app', '0007_rename_photo_article_lead_article_publication_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='contributor',
            name='photo',
            field=models.ImageField(default='contributor/empty.jpg', upload_to='contributor'),
        ),
        migrations.AlterField(
            model_name='article',
            name='views',
            field=models.IntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name='article',
            name='publisher',
            field=models.ManyToManyField(to='newsletter_app.publisher'),
        ),
    ]
