# Generated by Django 4.1.5 on 2023-01-31 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter_app', '0008_publisher_contributor_photo_alter_article_views_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='description',
            new_name='abstruct_problem',
        ),
        migrations.AddField(
            model_name='article',
            name='abstruct_contribution',
            field=models.TextField(default=''),
        ),
    ]
