# Generated by Django 4.1.5 on 2023-02-19 09:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter_app', '0010_alter_domain_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='publication_date',
            field=models.DateTimeField(default=datetime.date(2023, 2, 19)),
        ),
    ]
