# Generated by Django 4.1.5 on 2023-02-20 16:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter_app', '0012_alter_article_publication_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='publication_date',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1984), django.core.validators.MaxValueValidator(2023)]),
        ),
    ]
